"""The card brAIn writes the day it first knows something.

Every measurement in this add-on takes weeks. `rhythm` needs a fortnight
of weekdays, `closures` a full day of watching per hour of the week,
`habits` six separate days, `energy` two complete weeks before there is a
comparison. The whole of `house.py` exists because that silence is
indistinguishable from being broken — and a progress bar is the smallest
possible answer to it. It says *when*, and never *what*.

This is the other half. The moment a measurement first has an answer is
the one moment it is genuinely news, and it is the only moment at which a
card about it could not have been written last week. So each of the seven
fires **once**, when its own predicate first turns true, and what it
produces is an ordinary insight card built from that store's own numbers.

Four rules, and each of them is about not becoming a category.

**These are not the Insights tab's.** There is no `prompt_store` entry,
no hidden shipped category, no schedule and no refresh interval. A
category is a standing question somebody asked to have answered every
day; this is a fact that became knowable on a Tuesday. Mixing them would
put seven cards nobody chose onto a dashboard whose whole design is that
you chose what is on it.

**Once, and the settled key is what makes it once.** The card can be
deleted, regenerated by hand, or fail outright, and none of those may let
the next checks pass file it again — so what blocks a re-fire is an entry
in `_settled.json` keyed on the milestone, written the moment the card is
saved, and never removed by anything except an explicit refresh.

**"Materially changed" is defined per milestone, in the table, in the
units of that measurement.** A wake time that moves eleven minutes is the
same house; one that moves an hour and a half is a different household
routine and worth saying again. A thermal model that gains a room has
something new to say; one whose `k` moved in the third decimal does not.
There is no shared threshold because there is no shared unit, and a
single "has it changed" over seven different measurements would be a
number nobody could argue with.

**The store's numbers reach the prompt, and the store's floors stay in
the store.** Every predicate here reads `progress()` — the state, the
`have`/`need`, the `detail` — rather than re-deriving whether a
measurement is ready, because the floor that decides that belongs to the
module that owns the constant. What lives here is only the extra bar a
*card* needs on top of "there is an answer": one baseline is a
measurement and twenty-five is a picture of a house.

Stdlib plus the panel's own stores, so the test suite can drive the whole
table without the add-on runtime.
"""
from __future__ import annotations

import json
import logging
import os
import time
from pathlib import Path

import atomic_write

log = logging.getLogger("brain.milestones")

CARDS_DIR = Path(os.environ.get("BRAIN_KNOWLEDGE_CARDS", "/data/knowledge-cards"))
# The index that says a milestone has been reported, beside the cards
# rather than inside one: deleting a card must not re-arm it, which is
# the same reason `findings_store` keeps a settled ledger beside a list
# that is meant to empty.
SETTLED_FILE = CARDS_DIR / "_settled.json"

# One card per milestone and no history: the whole claim is "this became
# true", and a second copy of it from three weeks later is a different
# claim nobody made.
MAX_SUMMARY = 600
MAX_HIGHLIGHTS = 6
MAX_HTML_BYTES = 200_000


# ---------------------------------------------------------------------------
# The bar each measurement has to clear before it is worth a card
# ---------------------------------------------------------------------------
# Not floors — the stores own those. These are the extra "and enough of
# it to say something" each card needs, and they are here because they
# are properties of the CARD rather than of the measurement.

# One baseline is a measurement; a house is described by dozens.
BASELINE_ENTITIES = 25
# One fitted room cannot be compared with anything.
THERMAL_ROOMS = 2
# Three doors with a full day of watching each is the smallest set that
# can be said to describe a house rather than a door.
CLOSURE_ENTITIES = 3
CLOSURE_HOURS = 24

# What "materially changed" means, per measurement, in its own units.
WAKE_MOVE_MIN = 45.0


def _weekday(prog: dict) -> dict:
    return ((prog.get("detail") or {}).get("weekday") or {})


def _ready(prog: dict) -> bool:
    """A store that has an answer right now.

    `stale` is deliberately not ready: a milestone is news, and a
    measurement that stopped being rebuilt three weeks ago is not news
    about today.
    """
    return (prog or {}).get("state") == "ready"


# ---------------------------------------------------------------------------
# Predicates, marks and prompts
# ---------------------------------------------------------------------------

def _rhythm_ready(prog, payload):
    week = _weekday(prog)
    return _ready(prog) and bool(week.get("wakes")) and bool(week.get("settles"))


def _rhythm_mark(prog, payload):
    week = _weekday(prog)
    return {"wake": (week.get("wakes") or {}).get("minute"),
            "settle": (week.get("settles") or {}).get("minute")}


def _rhythm_moved(old, new):
    """A wake or settle time that moved more than three quarters of an hour.

    Around the clock, because a settle time either side of midnight is
    the ordinary case and a straight subtraction reports twenty minutes
    of drift as twenty-three hours of it — `rhythm.circular_spread`'s
    argument, in the one other place that compares two times of day.
    """
    for key in ("wake", "settle"):
        a, b = old.get(key), new.get(key)
        if a is None or b is None:
            continue
        gap = abs(float(a) - float(b)) % 1440.0
        if min(gap, 1440.0 - gap) > WAKE_MOVE_MIN:
            return True
    return False


def _rhythm_prompt(prog, payload):
    week = _weekday(prog)
    end = ((prog.get("detail") or {}).get("weekend") or {})
    wake, settle = week.get("wakes") or {}, week.get("settles") or {}
    lines = [
        "brAIn has just measured, for the first time, when this house gets "
        + "up and when it settles for the night. These are its own numbers, "
        + "from the first thing a PERSON does each day and the last:",
        f"- Weekdays: up about {wake.get('at')} (spread "
        + f"{round(float(wake.get('spread_min') or 0))} minutes over "
        + f"{wake.get('days')} days), settling about {settle.get('at')}.",
    ]
    weekend_wake = (end.get("wakes") or {}).get("at")
    if weekend_wake:
        lines.append(f"- Weekends: up about {weekend_wake}, settling about "
                     f"{(end.get('settles') or {}).get('at') or 'unmeasured'}.")
    else:
        lines.append("- Weekends: not measured yet — a weekend day arrives "
                     "twice a week, so it takes about five weeks.")
    return "\n".join(lines)


def _baselines_ready(prog, payload):
    return _ready(prog) and \
        int((prog.get("detail") or {}).get("with_buckets") or 0) >= BASELINE_ENTITIES


def _baselines_mark(prog, payload):
    detail = prog.get("detail") or {}
    return {"with_buckets": int(detail.get("with_buckets") or 0)}


def _baselines_moved(old, new):
    """The measured set doubling is a different house, not a fuller one."""
    was = int(old.get("with_buckets") or 0)
    return was > 0 and int(new.get("with_buckets") or 0) >= was * 2


def _baselines_prompt(prog, payload):
    detail = prog.get("detail") or {}
    entities = (payload or {}).get("entities") or {}
    named = [eid for eid, entry in sorted(entities.items())
             if isinstance(entry, dict) and entry.get("buckets")][:12]
    return "\n".join([
        "brAIn now knows what this house's sensors normally read at each "
        + "hour of the week — the measurement behind every \"unusual\" it "
        + "will ever report. Its own numbers:",
        f"- {detail.get('measured')} sensors read, "
        + f"{detail.get('with_buckets')} of them with a picture for every "
        + "hour of the week.",
        f"- {detail.get('flat')} never move at all, so they get no band.",
        f"- {detail.get('trends')} are drifting slowly enough that only a "
        + "trend line can see it.",
        "- Among the measured: " + ", ".join(named) + ".",
    ])


def _thermal_ready(prog, payload):
    return _ready(prog) and \
        int((prog.get("detail") or {}).get("rooms") or 0) >= THERMAL_ROOMS


def _thermal_mark(prog, payload):
    return {"rooms": int((prog.get("detail") or {}).get("rooms") or 0)}


def _thermal_moved(old, new):
    """A room gained is a room that can now be compared with the others."""
    return int(new.get("rooms") or 0) > int(old.get("rooms") or 0)


def _thermal_prompt(prog, payload):
    detail = prog.get("detail") or {}
    rooms = (payload or {}).get("rooms") or {}
    lines = [
        "brAIn has fitted a thermal model to this house's rooms — how fast "
        "each one loses heat, and how fast it gains it. Both are Newton's "
        f"numbers, measured against {detail.get('outdoor') or 'outdoors'} "
        "over a month of nights. The time constant is the number with an "
        "intuition behind it: how long the room holds its heat.",
    ]
    for eid, room in sorted(rooms.items(),
                            key=lambda kv: (kv[1] or {}).get("tau_h") or 0)[:8]:
        if not isinstance(room, dict):
            continue
        lines.append(
            f"- {room.get('area') or room.get('name') or eid}: holds its heat "
            f"about {round(float(room.get('tau_h') or 0), 1)} h"
            + (f", warms {round(float(room['gain']), 2)}°/h when heated"
               if room.get("gain") else ""))
    coldest = detail.get("coldest")
    if coldest is not None:
        lines.append(f"- The coldest night the month held was {coldest} "
                     "outside, which is what these were measured against.")
    return "\n".join(lines)


def _appliances_ready(prog, payload):
    return _ready(prog) and \
        int((prog.get("detail") or {}).get("profiled") or 0) >= 1


def _appliances_mark(prog, payload):
    detail = prog.get("detail") or {}
    return {"profiled": int(detail.get("profiled") or 0),
            "chore_capable": int(detail.get("chore_capable") or 0)}


def _appliances_moved(old, new):
    """A machine whose chore brAIn can now raise is a new capability."""
    return int(new.get("chore_capable") or 0) > int(old.get("chore_capable") or 0)


def _appliances_prompt(prog, payload):
    detail = prog.get("detail") or {}
    entities = (payload or {}).get("entities") or {}
    lines = [
        "brAIn has learned what this house's machines look like in watts — "
        + "measured per machine from its own ten days of readings, never a "
        + "wattage anybody typed. It can now tell running from idle, and a "
        + "quiet phase inside a cycle from a cycle that has ended:",
        f"- {detail.get('profiled')} machine(s) profiled; "
        + f"{detail.get('chore_capable')} of them named as a washer, dryer "
        + "or dishwasher, which is what a chore reminder needs.",
    ]
    for eid, entry in sorted(entities.items())[:8]:
        if not isinstance(entry, dict):
            continue
        lines.append(
            f"- {entry.get('name') or eid}: idles about "
            f"{round(float(entry.get('idle_w') or 0), 1)} W, runs above "
            f"{round(float(entry.get('threshold_w') or 0), 1)} W, and its "
            f"own quiet phases last up to "
            f"{round(float(entry.get('settle_min') or 0))} minutes.")
    return "\n".join(lines)


def _closures_ready(prog, payload):
    entities = (payload or {}).get("entities") or {}
    watched = [e for e in entities.values()
               if isinstance(e, dict)
               and len(e.get("buckets") or {}) >= CLOSURE_HOURS]
    return _ready(prog) and len(watched) >= CLOSURE_ENTITIES


def _closures_mark(prog, payload):
    entities = (payload or {}).get("entities") or {}
    return {"watched": len([e for e in entities.values()
                            if isinstance(e, dict)
                            and len(e.get("buckets") or {}) >= CLOSURE_HOURS])}


def _closures_moved(old, new):
    """Another three watched closures is a materially wider picture."""
    return int(new.get("watched") or 0) >= int(old.get("watched") or 0) + 3


def _closures_prompt(prog, payload):
    entities = (payload or {}).get("entities") or {}
    lines = [
        "brAIn has watched this house's doors, windows and locks for long "
        "enough to know what is normal for each hour of the week — which "
        "is what makes \"the back door is open\" a thing worth saying at "
        "23:40 and nothing at all at four in the afternoon. Its numbers, "
        "as the share of each entity's watched time spent open:",
    ]
    for eid, entry in sorted(entities.items())[:10]:
        if not isinstance(entry, dict):
            continue
        overall = entry.get("overall")
        lines.append(
            f"- {entry.get('name') or eid}: open about "
            f"{round(float(overall or 0) * 100)}% of the time, over "
            f"{len(entry.get('buckets') or {})} watched hours of the week.")
    return "\n".join(lines)


def _energy_ready(prog, payload):
    used = ((prog.get("detail") or {}).get("energy") or {})
    return _ready(prog) and bool(used.get("comparable"))


def _energy_mark(prog, payload):
    used = ((prog.get("detail") or {}).get("energy") or {})
    return {"this": used.get("this")}


def _energy_moved(old, new):
    """A week is a new week every week, so this one never re-fires here.

    The weekly report is what says what the electricity did; this card is
    about the comparison becoming possible at all, and that happens once.
    """
    return False


def _energy_prompt(prog, payload):
    detail = prog.get("detail") or {}
    used = detail.get("energy") or {}
    cost = detail.get("cost") or {}
    lines = [
        "brAIn can compare this house's electricity week on week for the "
        + "first time — two complete weeks of Home Assistant's own grid "
        + "meters, which is the earliest a comparison means anything:",
        f"- Last 7 days: {used.get('this')} {used.get('unit') or 'kWh'}; "
        f"the week before: {used.get('last')} {used.get('unit') or 'kWh'}"
        + (f" ({used.get('change_pct')}% change)."
           if used.get("change_pct") is not None else "."),
    ]
    if cost.get("this") is not None:
        # Only where Home Assistant made its own cost statistic. There is
        # no price to multiply by here, and inventing one is how a report
        # quotes a number belonging to a different sensor.
        lines.append(f"- Cost over the same window: {cost.get('this')}"
                     f"{cost.get('unit') or ''}.")
    return "\n".join(lines)


def _habits_ready(prog, payload):
    return _ready(prog) and \
        int((prog.get("detail") or {}).get("would_propose") or 0) >= 1


def _habits_mark(prog, payload):
    detail = prog.get("detail") or {}
    return {"would_propose": int(detail.get("would_propose") or 0)}


def _habits_moved(old, new):
    """More habits than before is more to offer; the same one is not."""
    return int(new.get("would_propose") or 0) > int(old.get("would_propose") or 0)


def _habits_prompt(prog, payload):
    detail = prog.get("detail") or {}
    return "\n".join([
        "brAIn has watched this house long enough to see something the "
        + "homeowner does BY HAND often enough to be a habit — the first "
        + "thing it can offer to do for them rather than report at them:",
        f"- {detail.get('presses')} hand-driven changes recorded over "
        + f"{prog.get('have')} separate days.",
        f"- {detail.get('would_propose')} of them regular enough to be worth "
        + "proposing as a routine.",
        f"- {detail.get('overrides')} times something was put back after an "
        + "automation moved it, which is the other half of the same signal.",
        "The proposals themselves are on the Proposals tab — do not repeat "
        + "them. Say what has become knowable and what it is based on.",
    ])


# The table. `store` names the measurement in `house.STORES`, which is
# also the key its loaded payload arrives under, and the id is that name
# — the vocabulary `/api/knowledge/house/{name}` and `get_house_model`
# already use, so a person reading one surface can look the other up.
#
# `energy` is therefore both a milestone here and a shipped category in
# `categories.py`. That overlap is deliberate and it is not a collision:
# two tables, two stores (`/data/knowledge-cards` against `/data/
# insights`), two routes, and two job ids (`milestone-energy` against
# `energy`). Nothing joins them, and `tests/test_milestones.py` is what
# says so — renaming the milestone to avoid the word would cost the one
# thing the shared vocabulary buys.
MILESTONES: list[dict] = [
    {"id": "rhythm", "store": "rhythm",
     "title": "When this house gets up",
     "ready": _rhythm_ready, "mark": _rhythm_mark, "moved": _rhythm_moved,
     "prompt": _rhythm_prompt},
    {"id": "baselines", "store": "baselines",
     "title": "What is normal here",
     "ready": _baselines_ready, "mark": _baselines_mark,
     "moved": _baselines_moved, "prompt": _baselines_prompt},
    {"id": "thermal", "store": "thermal",
     "title": "How these rooms hold heat",
     "ready": _thermal_ready, "mark": _thermal_mark, "moved": _thermal_moved,
     "prompt": _thermal_prompt},
    {"id": "appliances", "store": "appliances",
     "title": "What the machines look like in watts",
     "ready": _appliances_ready, "mark": _appliances_mark,
     "moved": _appliances_moved, "prompt": _appliances_prompt},
    {"id": "closures", "store": "closures",
     "title": "When the doors are usually open",
     "ready": _closures_ready, "mark": _closures_mark, "moved": _closures_moved,
     "prompt": _closures_prompt},
    {"id": "energy", "store": "energy",
     "title": "A week of electricity to compare against",
     "ready": _energy_ready, "mark": _energy_mark, "moved": _energy_moved,
     "prompt": _energy_prompt},
    {"id": "habits", "store": "habits",
     "title": "Something you do by hand",
     "ready": _habits_ready, "mark": _habits_mark, "moved": _habits_moved,
     "prompt": _habits_prompt},
]

MILESTONE_IDS = [m["id"] for m in MILESTONES]


def get(mile_id: str) -> dict | None:
    for m in MILESTONES:
        if m["id"] == mile_id:
            return m
    return None


# ---------------------------------------------------------------------------
# The prompt
# ---------------------------------------------------------------------------

FRAME = """brAIn has just finished measuring something about this home for the first time, and this card is how the homeowner finds out. It is not a report on a problem and not a recurring insight: it is one thing that has become knowable today and could not have been said last week.

WHAT WAS MEASURED — these are brAIn's OWN numbers, already computed. Use them. Do not re-derive them, and do not go looking for a fault:
{body}

Write the card about THAT. Say what is now known, in the homeowner's terms, with the real numbers and the real names above; then say what it lets brAIn do that it could not do before. Use your read-only tools only to put a friendly name on an entity id or to state one figure the numbers above imply — never to find new material, and never to turn this into a problem report."""


def prompt_for(entry: dict, prog: dict, payload: dict | None) -> str:
    """The one prompt for one milestone, from the store's own numbers."""
    return FRAME.format(body=entry["prompt"](prog, payload or {}))


# ---------------------------------------------------------------------------
# The settled index, and the cards
# ---------------------------------------------------------------------------

def _read_json(path: Path, fallback):
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return fallback
    return data if isinstance(data, type(fallback)) else fallback


def settled() -> dict:
    """`{milestone id: {"at": epoch, "mark": {...}}}`."""
    return _read_json(SETTLED_FILE, {})


def is_settled(mile_id: str) -> bool:
    return mile_id in settled()


def settle(mile_id: str, mark: dict, now: float | None = None) -> dict:
    data = settled()
    data[mile_id] = {"at": int(now or time.time()), "mark": dict(mark or {})}
    CARDS_DIR.mkdir(parents=True, exist_ok=True)
    atomic_write.write_json(SETTLED_FILE, data)
    return data[mile_id]


def unsettle(mile_id: str) -> bool:
    """Arm a milestone again. Only ever called by an explicit refresh."""
    data = settled()
    if mile_id not in data:
        return False
    del data[mile_id]
    atomic_write.write_json(SETTLED_FILE, data)
    return True


def card_path(mile_id: str) -> Path:
    entry = get(mile_id)
    if entry is None:
        raise ValueError(f"no milestone called {mile_id!r}")
    return CARDS_DIR / f"{entry['id']}.json"


def save_card(mile_id: str, obj: dict, mark: dict,
              because: str = "", now: float | None = None) -> dict:
    """Store one milestone card and settle the milestone in one act.

    The two together, because a card on disk that nothing settled fires
    again on the next pass and a settled milestone with no card is a
    thing the tab cannot show.
    """
    entry = get(mile_id)
    if entry is None:
        raise ValueError(f"no milestone called {mile_id!r}")
    now = time.time() if now is None else now
    html = obj.get("html") if isinstance(obj.get("html"), str) else ""
    if len(html.encode()) > MAX_HTML_BYTES:
        raise ValueError("generated visualization too large")
    highlights = obj.get("highlights")
    card = {
        "id": entry["id"],
        "kind": "milestone",
        "store": entry["store"],
        "title": str(obj.get("title") or entry["title"])[:120],
        "summary": str(obj.get("summary") or "")[:MAX_SUMMARY],
        "highlights": (highlights if isinstance(highlights, list) else [])
        [:MAX_HIGHLIGHTS],
        "html": html,
        "made_at": int(now),
        "made_because": because or f"milestone: {entry['id']} measured",
        "mark": dict(mark or {}),
    }
    CARDS_DIR.mkdir(parents=True, exist_ok=True)
    atomic_write.write_json(card_path(mile_id), card)
    settle(mile_id, mark, now)
    return card


def get_card(mile_id: str) -> dict | None:
    if get(mile_id) is None:
        return None
    return _read_json(card_path(mile_id), {}) or None


def list_cards() -> list[dict]:
    """Every milestone card there is, newest first."""
    out = []
    for entry in MILESTONES:
        card = get_card(entry["id"])
        if card:
            out.append(card)
    out.sort(key=lambda c: int(c.get("made_at") or 0), reverse=True)
    return out


# ---------------------------------------------------------------------------
# What is due
# ---------------------------------------------------------------------------

def due(snapshot: dict, payloads: dict | None = None,
        now: float | None = None) -> list[dict]:
    """The milestones that should be written now, in table order.

    Pure over what it is handed — a `house.snapshot()` and the loaded
    store payloads — so the checks pass, a test and a manual refresh all
    ask the same question of the same data. A milestone whose predicate
    raises is skipped and logged rather than taking the pass down: six
    cards and a log line beats none.
    """
    now = time.time() if now is None else now
    stores = (snapshot or {}).get("stores") or {}
    payloads = payloads or {}
    marks = settled()
    out = []
    for entry in MILESTONES:
        prog = stores.get(entry["store"]) or {}
        payload = payloads.get(entry["store"]) or {}
        try:
            if not entry["ready"](prog, payload):
                continue
            mark = entry["mark"](prog, payload)
            was = marks.get(entry["id"])
            if was is None:
                because = f"milestone: {entry['id']} measured"
            elif entry["moved"](was.get("mark") or {}, mark):
                because = f"milestone: {entry['id']} changed materially"
            else:
                continue
        except Exception as exc:  # noqa: BLE001 — one milestone, not the pass
            log.warning("milestone %s could not be evaluated: %s",
                        entry["id"], exc)
            continue
        out.append({"id": entry["id"], "store": entry["store"],
                    "title": entry["title"], "mark": mark,
                    "made_because": because,
                    "prompt": prompt_for(entry, prog, payload)})
    return out


__all__ = [
    "CARDS_DIR", "MILESTONES", "MILESTONE_IDS", "SETTLED_FILE", "card_path",
    "due", "get", "get_card", "is_settled", "list_cards", "prompt_for",
    "save_card", "settle", "settled", "unsettle",
]
